import type { Metadata } from "next";
import "@/styles/Global.scss";
import Providers from "./providers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
          <Header />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
